In [111]:
import pandas as pd
import numpy as np

casas = pd.read_csv("houses_sp.csv", sep=",")

1) há valores nulos que possam comprometer a análise dos dados?

In [112]:
casas.isnull().sum() * 100/casas.shape[0]

city                0.000000
area                0.489990
rooms               0.713986
bathroom            0.000000
parking spaces     21.797564
floor               0.000000
hoa                 0.000000
rent                0.000000
tax                 0.000000
insurance           0.000000
total               0.000000
page hits           0.000000
days available      0.000000
interactions        0.000000
weeks available     0.000000
type                0.000000
dtype: float64

! Por se tratar de uma base de dados de imóveis para aluguel, levando em consideração o tamanho da base de dados e o percentual de itens com dados nulos, 
vamos excluir as linhas com valores nulos nas colunas de area e quartos.

In [113]:
casas_filtrada = casas[casas["area"].notnull() & casas["rooms"].notnull()]

casas_filtrada.isnull().sum() * 100/casas_filtrada.shape[0]

city                0.000000
area                0.000000
rooms               0.000000
bathroom            0.000000
parking spaces     21.893156
floor               0.000000
hoa                 0.000000
rent                0.000000
tax                 0.000000
insurance           0.000000
total               0.000000
page hits           0.000000
days available      0.000000
interactions        0.000000
weeks available     0.000000
type                0.000000
dtype: float64

A presença de vagas de estacionamento pode ser fator determinante para o valor do aluguel, de forma que vamos transformar os valores nulos da coluna correspondente em 0, 
indicando ausência de vagas.

In [114]:
casas_filtrada["parking spaces"] = casas_filtrada["parking spaces"].fillna(0)

casas_filtrada.isnull().sum() * 100/casas_filtrada.shape[0]

C:\Users\lamar\AppData\Local\Temp\ipykernel_14968\3078411292.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casas_filtrada["parking spaces"] = casas_filtrada["parking spaces"].fillna(0)

city               0.0
area               0.0
rooms              0.0
bathroom           0.0
parking spaces     0.0
floor              0.0
hoa                0.0
rent               0.0
tax                0.0
insurance          0.0
total              0.0
page hits          0.0
days available     0.0
interactions       0.0
weeks available    0.0
type               0.0
dtype: float64

2) qual a relação entre o número de vagas de estacionamento e a média do total do aluguel, incluindo taxas, medida com base na mediana?

In [115]:
casas_filtrada.groupby("parking spaces").agg({"total": "median"})

                  total
parking spaces
0.0              2270.0
1.0              3609.0
2.0              5387.0
3.0              8609.0
4.0             11038.0
5.0             10813.5
6.0             11112.0
7.0             12515.0
8.0              9380.0
12.0            12005.0

! verifica-se uma correspondência direta entre as vagas de estacionamento e o aluguel, salvo casos pontuais, os quais precisam de análise mais detalhada.

3) porque imóveis com menos vagas de estacionamento podem apresentar valor de aluguel maior do que imóveis com mais vagas em algumas situações?

In [116]:
casas_filtrada[casas_filtrada["parking spaces"] == 4].describe()

,area,rooms,bathroom,parking spaces,hoa,rent,insurance,total,page hits,days available,interactions,weeks available
count,593.000000,593.000000,593.000000,593.0,593.000000,593.000000,593.000000,593.000000,593.000000,593.000000,593.000000,593.000000
mean,334.532884,3.677909,4.337268,4.0,2619.374368,7931.166948,115.500843,11808.170320,806.327150,79.635750,268.775717,11.158516
std,1006.010704,0.792150,1.194403,0.0,8343.153669,3832.113216,227.291500,10111.095962,506.962504,54.713463,168.987501,7.819879
min,70.000000,1.000000,1.000000,4.0,0.000000,1000.000000,13.000000,1091.000000,0.000000,0.000000,0.000000,0.000000
25%,213.000000,3.000000,4.000000,4.0,0.000000,4600.000000,64.000000,7603.000000,432.000000,50.000000,144.000000,7.000000
50%,260.000000,4.000000,4.000000,4.0,2380.000000,7925.000000,106.000000,11038.000000,720.000000,71.000000,240.000000,10.000000
75%,350.000000,4.000000,5.000000,4.0,3330.000000,10500.000000,144.000000,14769.000000,1116.000000,93.000000,372.000000,13.000000
max,24606.000000,9.000000,10.000000,4.0,200000.000000,20000.000000,5500.000000,222088.000000,4464.000000,303.000000,1488.000000,43.000000

In [117]:

casas_filtrada[casas_filtrada["parking spaces"] == 5].describe()

,area,rooms,bathroom,parking spaces,hoa,rent,insurance,total,page hits,days available,interactions,weeks available
count,234.000000,234.000000,234.000000,234.0,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000
mean,348.183761,3.816239,4.478632,5.0,1692.978632,8640.273504,117.017094,11574.606838,672.307692,60.260684,224.102564,8.397436
std,134.938376,0.799942,1.183566,0.0,2117.275556,5590.900011,72.330427,6359.401358,516.736581,37.198176,172.245527,5.312564
min,80.000000,2.000000,1.000000,5.0,0.000000,1870.000000,26.000000,2299.000000,0.000000,0.000000,0.000000,0.000000
25%,250.500000,3.000000,4.000000,5.0,0.000000,3356.250000,50.000000,5941.000000,360.000000,36.000000,120.000000,5.000000
50%,350.000000,4.000000,5.000000,5.0,0.000000,7362.500000,100.500000,10813.500000,558.000000,52.000000,186.000000,7.000000
75%,410.000000,4.000000,5.000000,5.0,3137.500000,12375.000000,165.750000,16967.750000,864.000000,83.000000,288.000000,11.750000
max,900.000000,8.000000,7.000000,5.0,8500.000000,20000.000000,254.000000,28314.000000,2700.000000,330.000000,900.000000,47.000000

In [118]:

casas_filtrada[casas_filtrada["parking spaces"] == 7].describe()

,area,rooms,bathroom,parking spaces,hoa,rent,insurance,total,page hits,days available,interactions,weeks available
count,21.000000,21.000000,21.000000,21.0,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,439.809524,4.000000,4.666667,7.0,1554.142857,10367.619048,149.476190,13859.857143,648.000000,57.523810,216.000000,8.000000
std,195.366737,0.774597,1.354006,0.0,2936.143802,3855.986132,54.103252,6490.650447,474.872614,29.220916,158.290871,4.207137
min,110.000000,3.000000,3.000000,7.0,0.000000,4000.000000,61.000000,4956.000000,108.000000,7.000000,36.000000,1.000000
25%,300.000000,4.000000,4.000000,7.0,0.000000,7000.000000,106.000000,9165.000000,324.000000,36.000000,108.000000,5.000000
50%,440.000000,4.000000,5.000000,7.0,0.000000,10800.000000,148.000000,12515.000000,540.000000,58.000000,180.000000,8.000000
75%,556.000000,4.000000,5.000000,7.0,890.000000,14000.000000,191.000000,17518.000000,792.000000,71.000000,264.000000,10.000000
max,1000.000000,6.000000,8.000000,7.0,8600.000000,15000.000000,226.000000,28791.000000,1908.000000,112.000000,636.000000,16.000000

In [119]:

casas_filtrada[casas_filtrada["parking spaces"] == 8].describe()

,area,rooms,bathroom,parking spaces,hoa,rent,insurance,total,page hits,days available,interactions,weeks available
count,133.000000,133.000000,133.000000,133.0,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,491.872180,3.639098,4.556391,8.0,549.924812,8896.067669,132.751880,11427.233083,867.248120,69.699248,289.082707,9.751880
std,309.156242,1.657574,2.916550,0.0,1668.435348,5645.330567,86.012015,7130.093479,632.689718,38.631120,210.896573,5.516375
min,38.000000,1.000000,1.000000,8.0,0.000000,2500.000000,32.000000,3195.000000,36.000000,7.000000,12.000000,1.000000
25%,250.000000,3.000000,2.000000,8.0,0.000000,4480.000000,68.000000,5235.000000,324.000000,51.000000,108.000000,7.000000
50%,500.000000,4.000000,5.000000,8.0,0.000000,8000.000000,121.000000,9380.000000,900.000000,59.000000,300.000000,8.000000
75%,750.000000,4.000000,6.000000,8.0,0.000000,14000.000000,211.000000,17076.000000,1260.000000,79.000000,420.000000,11.000000
max,1000.000000,10.000000,25.000000,8.0,14000.000000,45000.000000,677.000000,54427.000000,4068.000000,351.000000,1356.000000,50.000000

In [121]:

casas_filtrada[casas_filtrada["parking spaces"] == 12].describe()

,area,rooms,bathroom,parking spaces,hoa,rent,insurance,total,page hits,days available,interactions,weeks available
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0
25%,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0
50%,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0
75%,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0
max,1600.0,4.0,5.0,12.0,1.0,6900.0,104.0,12005.0,1044.0,91.0,348.0,13.0

! Observando os dados dos imoveis com 4, 5, 7, 8, e 12 vagas de estacionamento, consideramos que um fator que pesa para o valor total do aluguel é a taxa de condomínio,
representada pela coluna "hoa".

4) Como o valor do aluguel varia de acordo com o tipo de imóvel?

In [122]:
casas_filtrada.groupby(["type"])[["rent","total","hoa"]].describe()

         rent                                                           \
        count         mean          std    min     25%     50%     75%
type
flat   5234.0  4411.448987  3417.199812  600.0  2000.0  3175.0  5650.0
house  1823.0  5603.888097  4557.855333  500.0  2100.0  4300.0  8000.0

                 total               ...                       hoa  \
           max   count         mean  ...     75%       max   count
type                                 ...
flat   24000.0  5234.0  6401.453191  ...  8433.0  316922.0  5234.0
house  45000.0  1823.0  6370.772353  ...  8714.5   54427.0  1823.0


              mean          std  min    25%     50%     75%       max
type
flat   1496.774551  4266.572588  0.0  500.0  1054.5  2000.0  220000.0
house   119.174438   765.997898  0.0    0.0     0.0     0.0   15000.0

[2 rows x 24 columns]

! Verificamos que o valor do aluguel de casas tende a ser maior que o valor para apartamentos, contudo o valor total para apartamentos se torna maior em razão principalmente da taxa de condomínio (coluna "hoa").
! chama atenção o valor máximo da taxa de condomínio observada nesta anílise (220000), a qual é maior inclusive que o valor do aluguel, provavelmente indicando um erro na base de dados.

5) Quantos imóveis apresentam a taxa de condomínio maior que o valor do aluguel?

In [150]:
casas_filtrada[casas_filtrada["hoa"] > casas_filtrada["rent"]].sort_values("hoa", ascending=False)

,city,area,rooms,bathroom,parking spaces,floor,hoa,rent,tax,insurance,total,page hits,days available,interactions,weeks available,type
6099,São Paulo,340.0,5.0,4,2.0,7,220000,12000,1000,153,233153.0,1116,87,372,12,flat
4242,São Paulo,285.0,4.0,5,4.0,6,200000,20000,1834,254,222088.0,432,57,144,8,flat
1711,São Paulo,850.0,6.0,7,4.0,-,15000,13000,2465,196,30661.0,864,57,288,8,house
1256,São Paulo,488.0,4.0,3,3.0,-,14130,6400,1214,82,21826.0,432,86,144,12,house
5578,São Paulo,850.0,5.0,7,8.0,1,14000,4000,0,51,18051.0,324,36,108,5,flat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,São Paulo,75.0,2.0,1,0.0,5,1310,1283,0,17,2610.0,1188,113,396,16,flat
4153,São Paulo,100.0,3.0,2,1.0,5,1221,1200,38,16,2475.0,684,115,228,16,flat
5500,São Paulo,43.0,1.0,1,0.0,5,1195,680,220,9,2104.0,2448,120,816,17,flat
4404,São Paulo,54.0,2.0,1,1.0,1,990,780,0,10,1780.0,756,115,252,16,flat
3179,São Paulo,68.0,3.0,1,2.0,4,990,882,20,12,1904.0,1044,79,348,11,flat

! No total, 142 imóveis apresentam valor de taxa de condomínio maior que o valor do aluguel. Essas observações possivelmente representam erros na base de dados.

6) Há impacto significativo dos imóveis cujo valor do condomínio é maior que o valor do aluguel na análise global?

In [151]:
casas_filtrada[casas_filtrada["hoa"] > casas_filtrada["rent"]].value_counts().sum()/casas_filtrada.shape[0]

np.float64(0.020121864815077228)

! Um impacto de 2% numa base de dados de 7000 linhas parece representar um pequeno impacto na análise global.

7) Como se distribui o impacto dos imóveis com valor de condomínio maior que o valor de aluguel baseado no número de quartos? seria razoável excluir esses imoveis da base de dados?

In [167]:
casas_filtrada.groupby(["rooms"])[["rent", "hoa"]].agg(["size", "mean", "median",  "min", "max"])

       rent                                        hoa                       \
       size          mean   median    min    max  size         mean  median
rooms
1.0    1675   2485.293134   2090.0    500  15000  1675   546.864478   420.0
2.0    1674   3043.650538   2345.0    780  24000  1674   698.574074   600.0
3.0    2284   5384.958844   4300.0    882  30000  2284  1274.682574  1200.0
4.0    1191   8208.519731   8000.0   1000  45000  1191  2173.674223  2189.0
5.0     177   8460.892655   8000.0   2000  15000   177  2465.480226     0.0
6.0      32   7787.625000   7550.0   2472  15000    32   900.000000     0.0
7.0      16   8273.125000   8250.0   3800  15000    16     0.062500     0.0
8.0       5  12300.000000  10500.0   7000  25000     5    90.000000     0.0
9.0       1  12000.000000  12000.0  12000  12000     1   100.000000   100.0
10.0      2   9615.000000   9615.0   8330  10900     2     0.000000     0.0


       min     max
rooms
1.0      0    4320
2.0      0    7000
3.0      0    8043
4.0      0  200000
5.0      0  220000
6.0      0   15000
7.0      0       1
8.0      0     450
9.0    100     100
10.0     0       0

In [179]:
casas_filtrada[(casas_filtrada["rooms"] >= 5) & (casas_filtrada["rooms"] <= 6)].value_counts().sum()/casas_filtrada.shape[0]

np.float64(0.029615984129233386)

! Tomando por base os valores das médias de medianas para os valores de aluguel e taxa de condomínio, verificamos que o impacto na análise se concentra nos imóveis com 5 e 6 quartos. 
Novamente, temos um impacto da ordem de 2% da base de dados, o que pode ser considerado um impacto pouco significativo para a análise global. No entanto, caso se considere analisar recortes por número de quartos, a exclusão dessas observações deve ser considerada.